config/routes.rb
Rails.application.routes.draw do

  concern :paginatable do
    get '(page/:page)', action: :index, on: :collection, as: ''
  end
  root to: 'users#feed_photos'
  get '(page/:page)', to: 'users#feed_photos'

  get '/feed/albums', to: 'users#feed_albums'
  
  devise_for :users
  
  resources :users, concerns: :paginatable
  resources :photos, concerns: :paginatable
  resources :albums, concerns: :paginatable


  # devise_for :users, skip: :all

  # devise_for :users, controllers: {
  #   sessions: 'users/sessions',
  #   registrations: 'users/registrations'
  # }

  # devise_scope :user do
  #   get 'sign_in', to: 'devise/sessions#new'
  #   get 'sign_up', to: 'devise/registrations#new'
  # end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_many :albums, dependent: :destroy, validate: true
  has_many :photos, dependent: :destroy, validate: true
  
  mount_uploader :avatar, AvatarUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :trackable

  enum status: [:inactive, :active]

  validates :first_name, :last_name, presence: true
  validates :first_name, :last_name, length: { maximum: CONSTANTS::User::MAX_LENGTH_NAME }
  validates :email, length: { maximum: CONSTANTS::User::MAX_LENGTH_EMAIL }
  validates :email, uniqueness: true
  validates :password, length: { maximum: CONSTANTS::User::MAX_LENGTH_PASS }

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!
    before_action :set_user, only: [:edit, :update, :destroy]
    before_action :set_item_per_page, only: [:feed_albums, :feed_photos]

    def feed_photos
        redirect_to photos_path if user_signed_in? && current_user.is_admin? 
        @public_photo = Photo.where(mode: :public_mode)
        if user_signed_in? 
            @user_photo = current_user.photos
            @photos = @user_photo + @public_photo
            @photos.uniq!
        else
            @photos = @public_photo
            @photos = @photos
        end
        if @photos.kind_of?(Array)
            @photos = Kaminari.paginate_array(@photos).page(params[:page]).per(@item_per_page)
        else
            @photos = @photos.page(params[:page]).per(@item_per_page)
        end

    end
    
    def feed_albums
        redirect_to albums_path if user_signed_in? && current_user.is_admin? 
        @public_album = Album.where(mode: :public_mode)
        if user_signed_in? 
            @user_album = current_user.albums
            @albums = @user_album + @public_album
            @albums.uniq!
        else
            @albums = @public_album
            @albums = @albums.uniq
        end
        if @albums.kind_of?(Array)
            @albums = Kaminari.paginate_array(@albums).page(params[:page]).per(@item_per_page)
        else
            @albums = @albums.page(params[:page]).per(@item_per_page)
        end
    end

    def index
        @users = User.where(is_admin?: false ).page(params[:page]).per(@item_per_page)
    end

    def edit
    end

    def update
        respond_to do |format|
            if params[:active] = "true"
                @user.status = :active
            else
                @user.status = :inactive
            end
            
        if @user.update(user_params)
            format.html { redirect_to users_url, notice: 'User was successfully updated.' }
            format.json { render :show, status: :ok, location: @user }
        else
            format.html { render :edit }
            format.json { render json: @user.errors, status: :unprocessable_entity }
        end
        end
    end

    def destroy
        @user.destroy
        respond_to do |format|
        format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
        format.json { head :no_content }
        end
    end

    private
    def set_user
        @user = User.find(params[:id])
    end
    def set_item_per_page
        @item_per_page = 20
    end
    # Only allow admin to edit status on user
    def user_params
        params.require(:user).permit(:status)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<% content_for :header do %>
    <title> Edit Profile </title>
    <%# <link rel="stylesheet" href="/assets/user/edit_profile.css">  %>
    <%= stylesheet_link_tag 'user/edit_profile' %>
<% end %>
<%= content_for :script_link do %>
    <%= javascript_pack_tag 'update_account', 'data-turbolinks-track': 'reload' %>
<% end %>

<div class="container">
  <div class="row edit__container py-3">
    <div class="edit__header">
        <h3 class="edit__header_title"> Edit User Profile </h3>
            <%= link_to 'Back', users_path, class: "btn btn_primary edit__header__back__button"%>
    </div>
    <div class="seperator">
    </div>
    <%= form_with(model: @user, local: true, class: "edit__form mt-2", id: "form_photo") do |f| %>
      <div class="form-inline">
          <div class="col-sm-5"></div>
          <div class="edit_avatar col-sm-7 col-12">
              <div class="edit__avatar__image">
                    <%= image_tag(@user.avatar_url, alt: "avatar", class: "img-fluid") if @user.avatar? %>
                    <%= f.file_field :avatar, id: "btn_open_file" %>
                    <%= f.hidden_field :avatar_cache %>
                    <%#= image_tag "Photos/colorize_cat_image.jpg", alt: "avatar", class: "img-fluid" %>
                    <span id="btn__change_avatar"> Change </span>
              </div>
          </div>
      </div>
      <div class="edit__user__infor">
          <div class="form-inline">
              <label class="col-sm-5 col-12" for="first_name">  </label>
              <div class="col-sm-7 col-12">
                  <span class="edit_infor_title col-sm-7 col-12 "> Basic information </span>
              </div>
          </div>
          <div class="form-inline">
              <%= f.label :first_name, class: "col-sm-5 col-12" %>
              <%= f.text_field :first_name, class: "col-sm-7 col-12 form-control", placeholder: "First Name" ,readonly: true %>
          </div>
          <div class="form-inline">
              <%= f.label :last_name, class: "col-sm-5 col-12" %>
              <%= f.text_field :last_name, class: "col-sm-7 col-12 form-control", placeholder: "Last Name",readonly: true  %>
          </div>
          <div class="form-inline">
              <%= f.label :email, class: "col-sm-5 col-12" %>
              <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "col-sm-7 col-12 form-control",readonly: true  %>
          </div>

        <div class="form-inline">
            <%= f.label :password, class: "col-sm-5 col-12" %> 
            <%= f.password_field :password, autocomplete: "password", class: "col-sm-7 col-12 form-control", placeholder: "**********",readonly: true  %>
        </div>
        <div class="form-inline">
            <%= f.label :status, 'Active?', class: "col-sm-5 col-12" %>
            <div class="col-sm-7 col-12">
                <%= check_box_tag 'active', 'active', true, id: 'edit_active' %>
                <%#= f.check_box :status, id: "edit_active" %>
                <%# <input id="edit_active" type="checkbox" name="active"> %>
            </div>
        </div>

          <div class="form-inline">
              <div class="col-sm-5">
              </div>
              <div class="col-sm-7 col-12 mt-2">
                  <%= f.submit "Save", class: " btn btn-success" %>
              </div>
          </div>

      </div>
      <div class="form-inline">
            <%= form_errors(@user, { ul_class: "list-unstyled row w-100 mb-0 mt-3", li_class: "error col-12 col-sm-8 offset-sm-4" })%>
      </div>
    <% end %>

  </div>
</div>

app/views/users/feed_albums.html.erb
<% content_for :header do %>
    <%= stylesheet_link_tag 'user/feed_album'%>
    <%#= stylesheet_link_tag 'index'%>
    <title> Home page </title>
<% end %>
<div class="container">
    <div id="header__photo__list">
        <div class="header__button">
            <%= link_to 'PHOTO', root_path, class: "btn btn_primary_white" %>
            <button class="btn btn_primary"> ALBUM </button>
        </div>
    </div>
    <div class="row feed-list py-3">
        <% @albums.each do |album| %>
            <div class="col-lg-6 col-12 feed__item">
                <div class="card">
                    <div class="card-horizontal">
                        <div class="img-square-wrapper card__album" data-toggle="modal" data-target="#modal_photo_infor">
                            <%= show_album_image(album) %>
                        </div>
                        <div class="card-body">
                            <div class="feed__author">
                            <% @user = User.find(album.user_id) %>
                                <span class="feed__author-avatar"> <%= @user.first_name[0] << @user.last_name[0] %> </span>
                                <span class="author_name">  <%= @user.first_name << " " << @user.last_name %> </span>
                            </div>
                            <h4 class="card-title feed__title"> <%= album.title %> </h4>
                            <p class="card-text feed__description"> <%= album.description %> </p>
                            <div class="feed__footer">
                                <div class="feed__like">
                                    <span>
                                        <i class="fa fa-heart"></i>
                                        1999
                                    </span>
                                </div>
                                <div class="feed__time">
                                    17/07/2020
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Modal -->
            <section id="modal__photo" aria-label="section for modal">
                <div class="modal fade" id="modal_photo_infor" tabindex="-1" role="dialog" aria-labelledby="modal_photo_inforTitle" aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="modeal__photo__title"> <%= album.title %> </h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <div class="modal__photo__body">
                                    <div id="photo_slide_show" class="carousel slide" data-ride="carousel">
                                        <div class="carousel-inner">
                                            <div class="carousel-item active">
                                                <%= image_tag("Photos/colorize_cat_image.jpg", class: "d-block w-100", alt: "post image") %>
                                            </div>
                                            <div class="carousel-item ">
                                                <%= image_tag("Photos/first_project.jpg", class: "d-block w-100", alt: "post image") %>
                                            </div>
                                            <div class="carousel-item">
                                                <%= image_tag("Photos/HINHNEN.jpg", class: "d-block w-100", alt: "post image") %>
                                            </div>
                                        </div>
                                        <a class="carousel-control-prev" href="#photo_slide_show" role="button" data-slide="prev">
                                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                            <span class="sr-only">Previous</span>
                                        </a>
                                        <a class="carousel-control-next" href="#photo_slide_show" role="button" data-slide="next">
                                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                            <span class="sr-only">Next</span>
                                        </a>
                                    </div>
                                    <p class="modal_photo_description"> <%= album.description %> </p>
                                </div>
                            </div>
                            <!-- <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            <button type="button" class="btn btn-primary">Save changes</button>
                        </div> -->
                        </div>
                    </div>
                </div>
            </section>
        <% end %>
        
        <%= paginate @albums %>

</div>

app/views/users/feed_photos.html.erb
<% content_for :header do %>
    <%= stylesheet_link_tag 'user/feed_photos'%>
    <%#= stylesheet_link_tag 'index'%>
    <title> Home page </title>
<% end %>
<div class="container">
    <% if user_signed_in? %>
        <div id="header__photo__list">
            <div class="header__button">
                <button class="btn btn_primary"> PHOTO</button>
                <%= link_to 'ALBUM', feed_albums_path, class: "btn btn_primary_white"%>
            </div>
        </div>
    <% end %>
    <div class="row feed-list py-3">
      <% @photos.each do |photo| %>
            <div class="col-lg-6 col-12 feed__item">
                <div class="card">
                    <div class="card-horizontal">
                        <div class="img-square-wrapper" data-toggle="modal" data-target="#modal_photo_infor" >
                            <%= image_tag(photo.image_url, alt: 'Card image', class: 'card-image') %>
                        </div>
                        <div class="card-body">
                            <div class="feed__author">
                            <% @user = User.find(photo.user_id) %>
                                <span class="feed__author-avatar"> <%= @user.first_name[0] << @user.last_name[0] %>  </span>
                                <span class="author_name"> <%= @user.first_name << " " << @user.last_name %> </span>
                            </div>
                            <h4 class="card-title feed__title"> <%= photo.title %></h4>
                            <p class="card-text feed__description"> <%= photo.description %> </p>
                            <div class="feed__footer">
                                <div class="feed__like">
                                    <span>
                                        <i class="fa fa-heart"></i>
                                        1999
                                    </span>
                                </div>
                                <div class="feed__time">
                                    17/07/2020
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        <!-- Modal -->
        <section id="modal__photo" aria-label="section for modal">
            <div class="modal fade" id="modal_photo_infor" tabindex="-1" role="dialog" aria-labelledby="modal_photo_inforTitle" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="modeal__photo__title"><%= photo.title %> </h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <div class="modal__photo__body">
                                <%= image_tag photo.image_url, class: "modal__photo__image" %>
                                <p class="modal_photo_description"> <%= photo.description %></p>
                            </div>
                        </div>
                        <!-- <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="button" class="btn btn-primary">Save changes</button>
                    </div> -->
                    </div>
                </div>
            </div>
        </section>
    <% end %>
    </div>

    <%= paginate @photos %>

</div>

app/views/users/index.html.erb
 <% content_for :header do %>
    <title> Edit Profile </title>
    <%# <link rel="stylesheet" href="/assets/user/edit_profile.css">  %>
    <%= stylesheet_link_tag 'admin/manager_users' %>
<% end %>
 <div class="container">
     <div class="row feed-list py-3">
        <div class="table-responsive list__users">
            <table class="table-light table_users ">
                <thead>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>Email</th>
                    <th>Last Login</th>
                    <th></th>

                </thead>
                <tbody>
                    <tr>
                        <td colspan="5">
                            <hr>
                        </td>
                    </tr>
                    <% @users.each do |user| %>
                        <tr>
                            <td><%= user.first_name %></td>
                            <td> <%= user.last_name %> </td>
                            <td> <%= user.email %> </td>
                            <td> <%= user.last_sign_in_at %> </td>
                            <td>
                                <%= link_to 'Edit', edit_user_path(user), class: "btn btn-success" %>
                                <%= link_to 'Delete', user, method: :delete, data: {confirm: 'Are you sure' }, class: "btn btn-danger" %>
                            </td>
                        </tr>
                    <% end %>
                </tbody>
            </table>
        </div>

        <%= paginate @users %>

    </div>
</div>