config/routes.rb
Rails.application.routes.draw do

  concern :paginatable do
    get '(page/:page)', action: :index, on: :collection, as: ''
  end
  root to: 'users#feed_photos'
  get '(page/:page)', to: 'users#feed_photos'

  get '/feed/albums', to: 'users#feed_albums'
  
  devise_for :users
  
  resources :users, concerns: :paginatable
  resources :photos, concerns: :paginatable
  resources :albums, concerns: :paginatable


  # devise_for :users, skip: :all

  # devise_for :users, controllers: {
  #   sessions: 'users/sessions',
  #   registrations: 'users/registrations'
  # }

  # devise_scope :user do
  #   get 'sign_in', to: 'devise/sessions#new'
  #   get 'sign_up', to: 'devise/registrations#new'
  # end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/album.rb
class Album < ApplicationRecord
  belongs_to :user

  enum mode: [:private_mode, :public_mode]
  mount_uploaders :images, ImageUploader

  validates :title, :description, :mode, :images, presence: true
  validates :title, length: { maximum: CONSTANTS::Album::MAX_LENGTH_TITLE }
  validates :description, length: { maximum: CONSTANTS::Album::MAX_LENGTH_DESCRIPTION }
  validates :mode, inclusion: {in: [ "private_mode", "public_mode"]}

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_album, only: [:show, :edit, :update, :destroy]

  # GET /albums
  # GET /albums.json
  def index
    if current_user.is_admin? 
      @albums = Album.all
    else
      @albums = current_user.albums
    end
    @item_per_page = 20
    @item_per_page = 40  if current_user.is_admin? 
    if @albums.kind_of?(Array)
      @albums = Kaminari.paginate_array(@albums).page(params[:page]).per(@item_per_page)
    else
      @albums = @albums.page(params[:page]).per(@item_per_page)
    end
  end

  # GET /albums/1
  # GET /albums/1.json
  def show
  end

  # GET /albums/new
  def new
    @album = Album.new
  end

  # GET /albums/1/edit
  def edit
  end

  # POST /albums
  # POST /albums.json
  def create
    @album = current_user.albums.create(album_params)

    respond_to do |format|
      if @album.save
        format.html { redirect_to albums_url, notice: 'Album was successfully created.' }
        format.json { render :show, status: :created, location: @album }
      else
        format.html { render :new }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /albums/1
  # PATCH/PUT /albums/1.json
  def update
    respond_to do |format|
      if @album.update(album_params)
        format.html { redirect_to albums_url, notice: 'Album was successfully updated.' }
        format.json { render :show, status: :ok, location: @album }
      else
        format.html { render :edit }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.json
  def destroy
    @album.destroy
    respond_to do |format|
      format.html { redirect_to albums_url, notice: 'Album was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = Album.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def album_params
      params.require(:album).permit(:title, :description, :mode, {images: []})
    end
end

app/helpers/albums_helper.rb
module AlbumsHelper
  def show_album_image(model)
    html = ""
    html << image_tag(model.images[0].url, class: "album__image_1") if model.images[0] 
    html << image_tag(model.images[1].url, class: "album__image_2") if model.images[1] 
    html << image_tag(model.images[2].url, class: "album__image_3") if model.images[2]
    html.html_safe
  end
  
end

app/views/albums/_form.html.erb
<%= form_with(model: album, local: true, class: "edit__form mt-2", id: "form_album") do |form| %>
    <div class="form-row mb-2">
        <div class="col-12 col-md-6">
            <div class="form-group col-md-10 col-12">
                <%= form.label :title %>
                <%= form.text_field :title, class: "form-control", id: "form__edit__title" %>
            </div>
            <div class="form-group col-md-6 col-10 mt-4">
                <label for="form__edit__mode">Sharing mode</label>
                <%= form.select(:mode, [ [:Private, :private_mode], [ :Public, :public_mode]], {}, { class: "form-control", id: "form__edit__mode" } ) %>
            </div>
        </div>
        <div class="form-group col-12 col-md-6">
            <%= form.label :description %>
            <%= form.text_area :description, class: "form-control", id: "form__edit__description" %>
        </div>
    </div>
    <div class="form-group col-md-3 col-12">
        <div class="form__add__file">
            <%= form.file_field :images, multiple: true %>
            <%= form.hidden_field :images_cache %>
        </div>
    </div>
    <div class="row">
        <% album.images.each do |image| %>
            <div class="col-md-3 col-4">
                <%= image_tag(image.url, class: "form__add__image w-100", alt: "image") %>
            </div>
        <% end %>
    </div>
      <div class="form-group col-md-9 col-12">
        <%= form_errors(album) %>
      </div>
      <div class="form-group col-md-3 col-12 form__edit__button">
          <%= form.submit "Save", class: "btn btn-success" %>
          <% if album.persisted? %>
                  <%= link_to  album, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" do %>
                      <i class="far fa-trash-alt"> Delete </i>
                  <% end %>
          <% end %>
      </div>
     
<% end %>




 

app/views/albums/edit.html.erb
<% content_for :header do %>
    <title> Edit Album </title>
    <%# <link rel="stylesheet" href="/assets/user/edit_profile.css">  %>
    <%= stylesheet_link_tag 'album/edit_album' %>
<% end %>
<%= content_for :script_link do %>
    <%= javascript_pack_tag 'album_validate', 'data-turbolinks-track': 'reload' %>
<% end %>

<div class="container">
    <div class="row edit__container py-3">
        <div class="edit__header">
            <h3 class="edit__header_title"> Edit Album </h3>
            <%= link_to 'Back', albums_path, class: "btn btn_primary edit__header__back__button" %>
        </div>
        <div class="seperator">
        </div>
        <%= render 'form', album: @album %>
    </div>
</div>

app/views/albums/index.html.erb
<% content_for :header do %>
    <title> My Album </title>
    <%# <link rel="stylesheet" href="/assets/user/edit_profile.css">  %>
    <%= stylesheet_link_tag 'user/my_album' %>
<% end %>
<div class="container">
    <%= btn_add_new "Add New Album", new_album_path %>
    <div class="row feed-list py-3">                
      <% @albums.each do |album| %>
            <div class="album">
                <div class="album_title">
                    <span class="ellipsis"> <%= album.title %> </span>
                    <%= link_to edit_album_path(album) do %>
                       <i class="far fa-edit"></i>
                    <% end %>
                </div>
                <div class="album__image" data-toggle="modal" data-target="#modal_photo_infor">
                    <%= show_private_icons(album) %>
                    <%= show_album_image(album) %>
                    <%# <img class="album__image_1" src="../images/Photos/baitapdautien1.jpg" alt="user_image" /> %>
                </div>
            </div>
          <!-- Modal -->
          <section id="modal__photo" aria-label="section for modal">
              <div class="modal fade" id="modal_photo_infor" tabindex="-1" role="dialog" aria-labelledby="modal_photo_inforTitle" aria-hidden="true">
                  <div class="modal-dialog modal-dialog-centered" role="document">
                      <div class="modal-content">
                          <div class="modal-header">
                              <h5 class="modal-title" id="modeal__photo__title">album.title </h5>
                              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                  <span aria-hidden="true">&times;</span>
                              </button>
                          </div>
                          <div class="modal-body">
                              <div class="modal__photo__body">
                                  <div id="photo_slide_show" class="carousel slide" data-ride="carousel">
                                      <div class="carousel-inner">
                                          <div class="carousel-item active">
                                              <%= image_tag("Photos/colorize_cat_image.jpg", class: "d-block w-100", alt: "post image") %>
                                          </div>
                                          <div class="carousel-item ">
                                              <%= image_tag("Photos/first_project.jpg", class: "d-block w-100", alt: "post image") %>
                                          </div>
                                          <div class="carousel-item">
                                              <%= image_tag("Photos/HINHNEN.jpg", class: "d-block w-100", alt: "post image") %>
                                          </div>
                                      </div>
                                      <a class="carousel-control-prev" href="#photo_slide_show" role="button" data-slide="prev">
                                          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                          <span class="sr-only">Previous</span>
                                      </a>
                                      <a class="carousel-control-next" href="#photo_slide_show" role="button" data-slide="next">
                                          <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                          <span class="sr-only">Next</span>
                                      </a>
                                  </div>
                                  <p class="modal_photo_description">Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta perferendis officia expedita dolore obcaecati temporibus sit necessitatibus blanditiis fugiat vero.</p>
                              </div>
                          </div>
                          <!-- <div class="modal-footer">
                          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                          <button type="button" class="btn btn-primary">Save changes</button>
                      </div> -->
                      </div>
                  </div>
              </div>
          </section>
      <% end %>
    
    <%= paginate @albums %>
     
    </div>
</div>

app/views/albums/new.html.erb
<% content_for :header do %>
    <title> New Album </title>
    <%# <link rel="stylesheet" href="/assets/user/edit_profile.css">  %>
    <%= stylesheet_link_tag 'photo/new_photo' %>
<% end %>
<%= content_for :script_link do %>
    <%= javascript_pack_tag 'album_validate', 'data-turbolinks-track': 'reload' %>
<% end %>

<div class="container">
    <div class="row edit__container py-3">
        <div class="edit__header">
            <h3 class="edit__header_title"> New Album </h3>
            <%= link_to 'Back', albums_path, class: "btn btn_primary edit__header__back__button" %>
        </div>
        <div class="seperator">
        </div>
        <%= render 'form', album: @album %>
    </div>
</div>

app/views/albums/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @album.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @album.description %>
</p>

<p>
  <strong>Mode:</strong>
  <%= @album.mode %>
</p>

<p>
  <strong>User:</strong>
  <%= @album.user_id %>
</p>

<%= link_to 'Edit', edit_album_path(@album) %> |
<%= link_to 'Back', albums_path %>